name = "rewrite-url"
main = "worker.js"
compatibility_date = "2024-11-01"

[[kv_namespaces]]
binding = "LOGS"
id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"   # prod
preview_id = "yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy"  # preview

[vars]
LOG_READ_TOKEN = "change-me-very-strong"
